### ISSUE TITLE
Modern unit file

### ISSUE THREAD

**Issue by gcb** [openobserve/openobserve-docs#34]
is https://github.com/openobserve/openobserve-docs/blob/main/docs/operator-guide/systemd.md?plain=1#L29 still the recommended unit file? it makes no use of any of the sandboxing features or best practices.

Are patches on that direction welcome or these unit files are to be kept simple for use in already-sandboxed containers only?

**Comment by hengfeiyang** [comment]
This file only used for the user which simple run OpenObserve with binary in Linux. That the user use `./openobserve` to start service then we can use `systemd` to manage the service.

**Comment by gcb** [comment]
> This file only used for the user which simple run OpenObserve with binary in Linux. That the user use `./openobserve` to start service then we can use `systemd` to manage the service.

So, it *is* the recommended way to run it on linux?
